import Head from 'next/head';
import Image from 'next/image';
import { Navbar } from '../components/Navbar';
import { First } from '../components/Intro';
import { About } from '../components/About';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ishan | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <First />
      <About />
    </div>
  )
}
